parameters:
    peytz_peytzsend.api_client.class: SparkPost\SparkPost
    peytz_peytzsend.http_adapter.class: Ivory\HttpAdapter\Guzzle6HttpAdapter
    peytz_peytzsend.guzzle_client.class: GuzzleHttp\Client

services:
    peytz_peytzsend.http_adapter:
        class: "%peytz_peytzsend.http_adapter.class%"
        arguments: ["@peytz_peytzsend.client_adapter"]

    peytz_peytzsend.client_adapter:
        class: "%peytz_peytzsend.guzzle_client.class%"

    peytz_peytzsend.api_client:
        class: "%peytz_peytzsend.api_client.class%"
        arguments:
              - "@peytz_peytzsend.http_adapter"
              - { key: "%peytz_peytzsend.api_token%", host: "%peytz_peytzsend.api_host%" }